db:
  url: "jdbc:postgresql://localhost:5432/yourdatabase"
  user: "postgres"
  password: "password"
  driver: "org.postgresql.Driver"
  schema: "public"

scraping:
  url: "https://quotes.toscrape.com/"